import = [
  "~/.config/alacritty/themes/material_dark.toml",
  "~/.config/alacritty/linux.toml",
  "~/.config/alacritty/macos.toml",
]

[env]
TERM = "alacritty"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "LBracket"
mode = "~Search"
mods = "Control|Shift"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 100
lines = 50
