#!/bin/zsh
# Links the dotfiles to the home directory

# config
DOTFILES_DIR=$HOME/Workbench/Projects/personal/dotfiles

### remove old links
rm $HOME/.zshenv
rm -rf $XDG_CONFIG_HOME/zsh
rm -rf $XDG_CONFIG_HOME/alacritty
rm -rf $XDG_CONFIG_HOME/aerospace
rm -rf $XDG_CONFIG_HOME/neovide
rm -rf $XDG_CONFIG_HOME/lsd
rm $HOME/.tmux.conf

### zsh
mkdir $XDG_CONFIG_HOME/zsh
ln -s $DOTFILES_DIR/zsh/zshenv $HOME/.zshenv
ln -s $DOTFILES_DIR/zsh/zshrc $XDG_CONFIG_HOME/zsh/.zshrc
ln -s $DOTFILES_DIR/zsh/plugins $XDG_CONFIG_HOME/zsh/.zsh_plugins.txt

### alacritty
mkdir $XDG_CONFIG_HOME/alacritty
ln -s $DOTFILES_DIR/alacritty $XDG_CONFIG_HOME/alacritty

### tmux
ln -s $DOTFILES_DIR/tmux/tmux.conf $HOME/.tmux.conf

## aerospace
mkdir $XDG_CONFIG_HOME/aerospace
ln -s $DOTFILES_DIR/aerospace $XDG_CONFIG_HOME/aerospace

### neovide
ln -s $DOTFILES_DIR/neovide $XDG_CONFIG_HOME/neovide

### lsd
ln -s $DOTFILES_DIR/lsd $XDG_CONFIG_HOME/lsd
