general {
    # noctalia is now responsible for locking; previous hyprlock command kept for fallback.
    # lock_cmd = pidof hyprlock || hyprlock
    lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 150                                # 2.5min.
    on-timeout = ddcutil getvcp 60 | grep -q '0x0f' && ddcutil setvcp 10 0
    on-resume = ddcutil setvcp 10 70
}

listener {
    timeout = 300                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 330                                 # 5.5min
    on-timeout = ddcutil getvcp 60 | grep -q '0x0f' && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
