hl.on("hyprland.start", function()
  hl.exec_cmd("nm-applet &")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("waybar")
  hl.exec_cmd("swaync")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 25")
  hl.exec_cmd("udiskie")
  hl.exec_cmd("sleep 5 && onedrivegui")
  hl.exec_cmd("QT_QPA_PLATFORM=xcb synology-drive autostart")
end)
