##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# 1password
windowrule = stay_focused on, match:title Quick Access — 1Password
windowrule = pin on, match:title Quick Access — 1Password

# dolphin
windowrule = stay_focused on, match:title Create New Folder — Dolphin

# cs
windowrule = center on, match:title Counter-Strike 2
windowrule = immediate on, match:title Counter-Strike 2

# Deadlock
windowrule = immediate on, match:title Deadlock

# Old World
windowrule = immediate on, match:title OldWorld

# Steam apps
windowrule = immediate on, match:class ^(steam_app)

# telegram
windowrule = suppress_event activate activatefocus, match:class org.telegram.desktop
windowrule = suppress_event activate activatefocus, match:class com.ayugram.desktop

# IntelliJ
windowrule = stay_focused on, match:class jetbrains-idea, match:title win\d.*

# ueberzeugpp
windowrule = no_anim on, match:title ^(.*ueberzugpp.*)$

windowrule = suppress_event maximize, match:class .* # You'll probably like this.

# pdx-unlimiter
windowrule = no_focus on, match:class ^Pdx-Unlimiter$, match:title ^$, match:xwayland true
windowrule = no_shadow on, match:class ^Pdx-Unlimiter$, match:title ^$, match:xwayland true
windowrule = no_blur on, match:class ^Pdx-Unlimiter$, match:title ^$, match:xwayland true

# discord
windowrule = suppress_event activate activatefocus, match:class discord
