#!/bin/zsh

### Utils ###

# antidote
source /usr/share/zsh-antidote/antidote.zsh
antidote load
export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK
export ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE
export ZVM_VISUAL_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE

# keychain
eval $(keychain --eval --quiet)

# broot
source $CONFIG_DIR/broot/launcher/bash/br

# starship
eval "$(starship init zsh)"

# gh 1password
source $CONFIG_DIR/op/plugins.sh

# fzf
source <(fzf --zsh)

# zoxide
eval "$(zoxide init --cmd cd zsh)"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# jenv
# export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# nodenv
eval "$(nodenv init -)"

# initialize completions
compinit

# Fix slowness of pastes with zsh-syntax-highlighting.zsh
# from: https://gist.github.com/magicdude4eva/2d4748f8ef3e6bf7b1591964c201c1ab
pasteinit() {
    OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
    zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
    zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish
